/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TransactionOverrides } from "./common";
import { FaucetWallet } from "./FaucetWallet";

export class FaucetWalletFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<FaucetWallet> {
    return super.deploy(overrides) as Promise<FaucetWallet>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): FaucetWallet {
    return super.attach(address) as FaucetWallet;
  }
  connect(signer: Signer): FaucetWalletFactory {
    return super.connect(signer) as FaucetWalletFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FaucetWallet {
    return new Contract(address, _abi, signerOrProvider) as FaucetWallet;
  }
}

const _abi = [
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_token",
        type: "address"
      },
      {
        name: "_tokenAmount",
        type: "uint256"
      },
      {
        name: "_ethAmount",
        type: "uint256"
      }
    ],
    name: "updateFaucet",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "to",
        type: "address"
      }
    ],
    name: "transfer",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060008054600160a060020a031916331790556102f2806100326000396000f3fe60806040526004361061004b5763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416631a69523081146100505780634c1b3c9a14610085575b600080fd5b34801561005c57600080fd5b506100836004803603602081101561007357600080fd5b5035600160a060020a03166100c4565b005b34801561009157600080fd5b50610083600480360360608110156100a857600080fd5b50600160a060020a038135169060208101359060400135610217565b600054600160a060020a0316331461013d57604080517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152600a60248201527f6f6e6c79206f776e657200000000000000000000000000000000000000000000604482015290519081900360640190fd5b600254604051600160a060020a0383169180156108fc02916000818181858888f19350505050158015610174573d6000803e3d6000fd5b50600154600354604080517fa9059cbb000000000000000000000000000000000000000000000000000000008152600160a060020a03858116600483015260248201939093529051919092169163a9059cbb9160448083019260209291908290030181600087803b1580156101e857600080fd5b505af11580156101fc573d6000803e3d6000fd5b505050506040513d602081101561021257600080fd5b505050565b600054600160a060020a0316331461029057604080517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152600a60248201527f6f6e6c79206f776e657200000000000000000000000000000000000000000000604482015290519081900360640190fd5b6001805473ffffffffffffffffffffffffffffffffffffffff1916600160a060020a03949094169390931790925560035560025556fea165627a7a7230582040306ba0a7d7710d3b8c9d403622b83ff42daf52b66f0346ea5894d52b836ab90029";
